apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: odoo-postgres
  labels:
    app: odoo
spec:
  selector:
    matchLabels:
      app: odoo
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo
        tier: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/pgdata
      volumes:         
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-postgres
  labels:
    app: odoo
spec:
  ports:
    - port: 5432
  selector:
    app: odoo
    tier: postgres 
  type: LoadBalancer     
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi